spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: test1234

server:
  port: 80
test : 哈哈哈
user:
  userId: 123456
  userName: duxin
  password: Qqwert12345..